### ISSUE TITLE
test_http_header_util.test_parse_invalid_uri fails in python nightly (3.10.X)

### ISSUE THREAD

**Issue by quasi-mod** [GoogleChromeLabs/pywebsocket3#14]
Travis CI fails when executing `test_http_header_util.test_parse_invalid_uri` on python version nightly. 
([execution detail](https://travis-ci.com/github/GoogleChromeLabs/pywebsocket3/jobs/372366099))

It seems like something has changed in `urllib.parse.urlparse`, but since this is still a nightly build and nothing is supposed to be changed with urllib (reference [here](https://docs.python.org/3.10/whatsnew/3.10.html)), nothing should be done until anything is confirmed (or fixed).

**Comment by ricea** [comment]
Fixed in #22. It was actually a version comparison issue ('3.10.X' < '3.8.X').
