### ISSUE TITLE
os.popen3 not present in Python 3

### ISSUE THREAD

**Issue by donny-dont** [GoogleChromeLabs/pywebsocket3#17]
I'm currently working through running WebKit's Python infrastructure using Python 3 on Windows without Cygwin. The `run-webkit-tests` script starts up a web socket server from the web-platform-tests. It dies in `wrap_popen3_for_win` because `os.popen3` is not defined in Python 3.

If overriding os.popen3 is required then a check should probably done as to whether its present in the `os` module.

**Comment by ricea** [comment]
Thanks! I will take a look.

**Comment by ricea** [comment]
Do you need the Cygwin support? I think the only reason we kept it was a rumour that WebKit was using it. If I remove the Cygwin support, then this gets much easier.

**Comment by donny-dont** [comment]
For our ports, WinCairo and PlayStation, we don't need cygwin support at all. Currently 🍎 is still using Cygwin in their AppleWin port. It would be nice if they stopped using it but I'll let one of them chime in.

@JonWBedard @gsnedders

**Comment by gsnedders** [comment]
Pretty sure we're unlikely to move away from Cygwin in the near future, at least. @JonWBedard would know better than me, though, and know more about longer term plans.

**Comment by JonWBedard** [comment]
We don't have a clear long-term plan for Windows at the moment, so the Cygwin status-quo will remain for at least the next year

**Comment by donny-dont** [comment]
Thanks @ricea !
