### ISSUE TITLE
Incorrect copyright header

### ISSUE THREAD

**Issue by quidity** [GoogleChromeLabs/pywebsocket3#4]
https://github.com/GoogleChromeLabs/pywebsocket3/blob/89c9228434100e4dabb19f61d0d4f55625940638/mod_pywebsocket/websocket_server.py#L1

I notice this copyright header has 202 as the year, this is likely a mistake.

**Comment by ricea** [comment]
Thanks!

@quasi-mod could you look at this when you have time?

**Comment by quasi-mod** [comment]
Fixed on PR #5 
Thank you!
